# These are supported funding model platforms

github: [Technical-Shubham-tech]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: sanidhy
custom: https://www.buymeacoffee.com/sanidhy
